/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 05:08:57 GMT 2020
 */

package evo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import evo.MyClass;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyClass_ESTest extends MyClass_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("{(')Ok7,g");
      myClass0.reverseString("CqQn-X?!g'");
      myClass0.reverseString("{(')Ok7,g");
      int int0 = 58;
      myClass0.isPrimeNum(58);
      String string0 = "0W#W_U";
      myClass0.reverseString("0W#W_U");
      myClass0.IsPalindrome1(".kY*&Jl6)%");
      myClass0.IsPalindrome1(",:a-jj");
      myClass0.IsPalindrome1("AL:D05\"<c1A");
      // Undeclared exception!
      try { 
        myClass0.addBinary("4,v@>*G8$@A", "g,7kO)'({");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"4,v@>*G8$@A\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("jj-a:,");
      myClass0.isHappy(2695);
      myClass0.IsPalindrome1(",:a-jj");
      myClass0.isHappy(2695);
      myClass0.getNext(0);
      // Undeclared exception!
      myClass0.fib(30);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString(";||u1~T-=F54u7j ~)");
      myClass0.reverseString("evo.MyClass");
      myClass0.isPrimeNum(0);
      myClass0.selfDividing(1753);
      myClass0.IsPalindrome1(")~ j7u45F=-T~1u||;");
      myClass0.getGCD(0, 0);
      myClass0.selfDividing((-2919));
      myClass0.IsPalindrome1(")~ j7u45F=-T~1u||;");
      myClass0.selfDividing(100);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("ahimi)");
      myClass0.reverseString("E:g_");
      myClass0.getNext(10);
      myClass0.reverseString("ahimi)");
      myClass0.containsString("_g:E", ")imiha");
      myClass0.lcm(10, 1);
      myClass0.getNext(1);
      myClass0.fib(1);
      myClass0.isPrimeNum(10);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.selfDividing(0);
      myClass0.isPrimeNum(48);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.isLeapYear((-3074));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      String string0 = "";
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("WinB4IC");
      myClass0.reverseString("CI4BniW");
      myClass0.reverseString("WinB4IC");
      myClass0.IsPalindrome1("WinB4IC");
      myClass0.reverseString("");
      myClass0.IsPalindrome1("Wbj");
      myClass0.containsString("CI4BniW", "WinB4IC");
      myClass0.containsString("", "WinB4IC");
      int int0 = (-3288);
      myClass0.isHappy((-3288));
      // Undeclared exception!
      try { 
        myClass0.IsPalindrome1((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      // Undeclared exception!
      try { 
        myClass0.containsString((String) null, "6U");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      myClass0.lcm(0, (-2369));
      int int0 = 889;
      myClass0.fib(int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      myClass0.isPrimeNum(4007);
      myClass0.containsString("o`c9J~P3", "AYph>\"!15k]QTdMZA&");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.IsPalindrome1(" Z(/WD!,r&.WTi");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.lcm(400, 400);
      myClass0.containsString("|ETYjR47lWNofW", "k");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.containsString("h_y}PwPA&S1M+", "");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("Z-=b^;544q");
      myClass0.reverseString("|z,3");
      myClass0.reverseString("A}");
      myClass0.reverseString("Z-=b^;544q");
      int int0 = (-4);
      myClass0.isLeapYear((-4));
      String string0 = null;
      // Undeclared exception!
      try { 
        myClass0.containsString((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      String string0 = "";
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("O&WE7L#,r\".L|");
      myClass0.reverseString("");
      int int0 = (-720);
      myClass0.lcm((-720), (-720));
      myClass0.getGCD((-720), (-720));
      myClass0.isLeapYear(720);
      myClass0.reverseString("P>");
      myClass0.reverseString("O&WE7L#,r\".L|");
      String string1 = "3w#~jBxC*Ma";
      String string2 = "";
      // Undeclared exception!
      try { 
        myClass0.reverseString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("G@\"56kG");
      myClass0.containsString("evo.MyClass", "evo.MyClass");
      myClass0.getNext(2927);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString(">Ji8N;PE5");
      myClass0.isLeapYear(804);
      myClass0.isLeapYear(1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.lcm(0, 400);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      myClass0.fib(0);
      myClass0.isHappy(1182);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.IsPalindrome1("t!Sq}}4wZDqg~U'");
      myClass0.isHappy(2);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      // Undeclared exception!
      try { 
        myClass0.lcm(0, 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.IsPalindrome1("");
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.selfDividing((-1));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.isPrimeNum(1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.isPrimeNum(4);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString(";~'yuv$q");
      myClass0.isHappy((-49));
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.fib((-1680));
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.isLeapYear(0);
      myClass0.reverseString("G");
      myClass0.IsPalindrome1("G");
      myClass0.isHappy(908);
      myClass0.selfDividing(0);
      myClass0.isPrimeNum(908);
      myClass0.isPrimeNum(0);
      myClass0.IsPalindrome1("yFlTkpB{4Ndq{ChB[zz");
      myClass0.isLeapYear(18);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("i92FfSXT!3fJT9");
      myClass0.reverseString("i92FfSXT!3fJT9");
      myClass0.reverseString("");
      myClass0.getGCD((-2), (-2));
      myClass0.IsPalindrome1("fw'H");
      myClass0.getGCD(0, (-3081));
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("evo.MyClass");
      myClass0.reverseString("");
      myClass0.reverseString("ssalCyM.ove");
      myClass0.selfDividing(463);
      myClass0.isLeapYear(0);
      myClass0.lcm(1858, 0);
      myClass0.isLeapYear(100);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.getNext(16);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("B");
      myClass0.reverseString("B");
      String string0 = "0OV'xgN";
      myClass0.reverseString("0OV'xgN");
      // Undeclared exception!
      try { 
        myClass0.addBinary("D_8L%!<GRta0fl;K", "");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"D_8L%!<GRta0fl;K\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("?6x1\" Ll8-QB693Z_(]");
      myClass0.reverseString("3{oSU*/'R{#<D!R-");
      myClass0.reverseString("");
      myClass0.isLeapYear((-328));
      myClass0.selfDividing((-328));
      myClass0.reverseString("?6x1\" Ll8-QB693Z_(]");
      myClass0.reverseString("](_Z396BQ-8lL \"1x6?");
      myClass0.selfDividing(0);
      myClass0.isPrimeNum(0);
      myClass0.getNext(0);
      int int0 = (-82);
      myClass0.isHappy((-82));
      // Undeclared exception!
      try { 
        myClass0.reverseString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      myClass0.fib((-1352));
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("cl<k'k'KSjy=7wFA\"");
      myClass0.reverseString("cl<k'k'KSjy=7wFA\"");
      myClass0.isHappy((-1352));
      myClass0.lcm(0, (-1352));
      myClass0.isPrimeNum(0);
      myClass0.lcm(1, 0);
      myClass0.containsString("kd^IejvaC", "");
      myClass0.isHappy(1);
      myClass0.getGCD(0, (-1352));
      myClass0.getGCD((-462), 0);
      myClass0.reverseString("");
      myClass0.containsString("evo.MyClass", "6|U");
      int int0 = 1992;
      myClass0.lcm(0, 1992);
      // Undeclared exception!
      try { 
        myClass0.containsString((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("evo.MyClass", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      myClass0.reverseString("");
      myClass0.reverseString("A h");
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.isHappy((-64));
      myClass0.lcm(48, 2211);
      myClass0.lcm((-64), (-898));
      myClass0.containsString("Evo.MyClass", "Evo.MyClass");
      myClass0.reverseString("h A");
      myClass0.IsPalindrome1("");
      myClass0.reverseString("");
      myClass0.getNext(48);
      myClass0.isHappy((-898));
      myClass0.fib((-28736));
      myClass0.isPrimeNum(2211);
      myClass0.getNext(0);
      myClass0.containsString("A h", "%z");
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      String string0 = "";
      myClass0.reverseString("");
      String string1 = "evo.MyClass";
      myClass0.containsString("evo.MyClass", "");
      int int0 = 0;
      myClass0.isPrimeNum(0);
      int int1 = 0;
      myClass0.reverseString("");
      int int2 = (-181);
      myClass0.getGCD(0, (-181));
      myClass0.reverseString("");
      String string2 = "C(vzx^VAGLFbD2";
      myClass0.reverseString("C(vzx^VAGLFbD2");
      // Undeclared exception!
      myClass0.fib(181);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      MyClass myClass0 = new MyClass();
      String string0 = "";
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("");
      myClass0.reverseString("");
      int int0 = (-3762);
      myClass0.lcm((-3762), (-3762));
      myClass0.lcm((-1), (-3762));
      myClass0.selfDividing((-1));
      myClass0.reverseString("");
      myClass0.getNext((-3762));
      // Undeclared exception!
      try { 
        myClass0.addBinary("", "");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }
}
